set_project("CMSIS-DSP-MSPM0")
toolchain("arm-none-eabi")
    set_kind("standalone")
    set_toolset("cc", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-gcc.exe")
    set_toolset("cxx", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-g++.exe")
    set_toolset("as", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-as.exe")
    set_toolset("ld", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-ld.exe")
    set_toolset("ar", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-ar.exe")
    set_toolset("nm", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-nm.exe")
    set_toolset("strip", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-strip.exe")
    set_toolset("objcopy", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-objcopy.exe")
    set_toolset("objdump", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-objdump.exe")
toolchain_end()

toolchain("tiarmclang")
    set_kind("standalone")
    set_toolset("cc", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe")
    set_toolset("cxx", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe")
    set_toolset("as", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmasm.exe")
    set_toolset("ld", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmlnk.exe")
    set_toolset("ar", "C:/SysGCC/arm-eabi/bin/arm-none-eabi-ar.exe") 
    set_toolset("nm", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmnm.exe")
    set_toolset("strip", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmstrip.exe")
    set_toolset("objcopy", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmobjcopy.exe")
    set_toolset("objdump", "clang@C:/ti/ccstheia141/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmobjdump.exe")
toolchain_end()


target("cmsis-dsp-mspm0-gcc")
	set_plat("cross")
	set_arch("armeabi")
    set_kind("static")
    add_includedirs("$(projectdir)/Include")
    add_includedirs("$(projectdir)/Core/Include")
    add_includedirs("$(projectdir)/PrivateInclude")
    add_files("**.c")
    add_cflags("-mcpu=cortex-m0plus -march=armv6-m -mthumb -mfloat-abi=soft -O2 -ffunction-sections -fdata-sections -g -gdwarf-3 -gstrict-dwarf -Wall")
    set_toolchains("arm-none-eabi")

target("cmsis-dsp-mspm0-ticlang")
	set_plat("cross")
	set_arch("armeabi")
    set_kind("static")
    add_includedirs("$(projectdir)/Include")
    add_includedirs("$(projectdir)/Core/Include")
    add_includedirs("$(projectdir)/PrivateInclude")
    add_files("**.c")
    add_cflags("-march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -O2")
    add_cflags("-gdwarf-3")
    set_toolchains("tiarmclang")
